name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Sass
        run: npm install sass

      - name: Compile Sass
        run: npx sass static-html/sass/style.sass static-html/css/style.css

      - uses: akhileshns/heroku-deploy@v3.0.5
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "gcs-docker-githubactions"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
